apiVersion: apps/v1 
kind: Deployment
metadata:
  name: k8shtml-deployment
spec:
  selector:
    matchLabels:
      app: k8shtml
  replicas: 1 
  template:
    metadata:
      labels:
        app: k8shtml
    spec:
      containers:
      - name: k8shtml
        image: alexsandr/k8s_html
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-k8shtml
  labels:
    app : k8shtml
spec:
  selector : 
    app : k8shtml
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: NodePort
